# Generated by Django 4.1.3 on 2023-02-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etldata', '0002_alter_part_excel_file_alter_part_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='upload_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='pass_percentage',
            field=models.FloatField(default=0),
        ),
    ]
