# Generated by Django 4.1.3 on 2022-12-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=30)),
                ('part_name', models.CharField(max_length=100)),
                ('length_units', models.CharField(max_length=50, null=True)),
                ('control', models.CharField(max_length=100, null=True)),
                ('nom', models.FloatField(null=True)),
                ('measurement', models.FloatField(null=True)),
                ('tolerance', models.FloatField(null=True)),
                ('deviation', models.FloatField(null=True)),
                ('test_result', models.CharField(choices=[('Fail', 'Fail'), ('Pass', 'Pass')], max_length=10, null=True)),
                ('out_of_tolerance', models.FloatField(null=True)),
                ('upload_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('excel_file', models.FileField(upload_to='')),
                ('upload_time', models.DateTimeField()),
            ],
        ),
    ]
