# Generated by Django 4.1.3 on 2022-12-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etldata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='excel_file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='part',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
